from __future__ import annotations

from enum import StrEnum, auto
from typing import Any

__all__ = ["ErrorCode", "ERROR_STATUS_MAP", "AppError"]


class ErrorCode(StrEnum):
    SUCCESS = auto()

    AUTH_INVALID_OTP = auto()
    AUTH_EXPIRED_OTP = auto()
    AUTH_MAX_ATTEMPTS = auto()
    AUTH_BLOCKED = auto()
    AUTH_INVALID_TOKEN = auto()
    AUTH_TOKEN_EXPIRED = auto()
    AUTH_TOKEN_REVOKED = auto()
    AUTH_UNAUTHORIZED = auto()
    AUTH_FORBIDDEN = auto()
    AUTH_PHONE_EXISTS = auto()
    AUTH_PHONE_NOT_FOUND = auto()
    AUTH_INVALID_REFRESH = auto()
    AUTH_2FA_REQUIRED = auto()
    AUTH_2FA_INVALID = auto()
    AUTH_DEVICE_REQUIRED = auto()
    AUTH_DEVICE_SESSION_EXPIRED = auto()

    VALIDATION_MISSING_FIELD = auto()
    VALIDATION_INVALID_PHONE = auto()
    VALIDATION_INVALID_EMAIL = auto()
    VALIDATION_INVALID_AMOUNT = auto()
    VALIDATION_INVALID_CURRENCY = auto()
    VALIDATION_INVALID_LANGUAGE = auto()
    VALIDATION_INVALID_TIMEZONE = auto()
    VALIDATION_INVALID_UUID = auto()
    VALIDATION_INVALID_ENUM = auto()
    VALIDATION_EXCEEDS_MAX_LENGTH = auto()
    VALIDATION_BELOWS_MIN_LENGTH = auto()
    VALIDATION_INVALID_JSON = auto()
    VALIDATION_INVALID_CONTENT_TYPE = auto()
    VALIDATION_BODY_TOO_LARGE = auto()
    VALIDATION_IDEMPOTENCY_REUSE = auto()
    VALIDATION_INVALID_PARAMETER = auto()

    ORDER_NOT_FOUND = auto()
    ORDER_ALREADY_PAID = auto()
    ORDER_ALREADY_PROCESSED = auto()
    ORDER_EXPIRED = auto()
    ORDER_CANCELLED = auto()
    ORDER_INVALID_STATUS = auto()

    PLAN_NOT_FOUND = auto()
    PLAN_UNAVAILABLE = auto()
    PLAN_INACTIVE = auto()
    PLAN_COUNTRY_UNSUPPORTED = auto()
    PLAN_HAS_ORDERS = auto()

    WALLET_INSUFFICIENT_BALANCE = auto()
    WALLET_NOT_FOUND = auto()
    WALLET_TRANSACTION_FAILED = auto()

    PAYMENT_FAILED = auto()
    PAYMENT_TIMEOUT = auto()
    PAYMENT_DECLINED = auto()
    PAYMENT_CANCELLED = auto()
    PAYMENT_INVALID_SIGNATURE = auto()
    PAYMENT_DUPLICATE = auto()
    PAYMENT_REFUND_FAILED = auto()
    PAYMENT_METHOD_UNSUPPORTED = auto()

    PROVIDER_UNAVAILABLE = auto()
    PROVIDER_TIMEOUT = auto()
    PROVIDER_INVALID_RESPONSE = auto()
    PROVIDER_AUTH_FAILED = auto()
    PROVIDER_RATE_LIMITED = auto()
    PROVIDER_INSUFFICIENT_BALANCE = auto()
    PROVIDER_BUNDLE_NOT_FOUND = auto()

    RATE_LIMIT_EXCEEDED = auto()
    RATE_LIMIT_AUTH_EXCEEDED = auto()

    INTERNAL_ERROR = auto()
    DATABASE_ERROR = auto()
    DATABASE_CONNECTION_ERROR = auto()
    DATABASE_INTEGRITY_ERROR = auto()
    MAINTENANCE_MODE = auto()

    USER_NOT_FOUND = auto()
    USER_ACCOUNT_DELETED = auto()

    ESIM_NOT_FOUND = auto()
    ESIM_EXPIRED = auto()
    ESIM_INVALID_STATUS = auto()

    INVENTORY_NOT_FOUND = auto()
    INVENTORY_INSUFFICIENT_STOCK = auto()
    INVENTORY_ICCID_DUPLICATE = auto()
    INVENTORY_INVALID_FILE = auto()
    INVENTORY_ICCID_INVALID = auto()

    ACTIVATION_FAILED = auto()
    ACTIVATION_TIMEOUT = auto()
    ACTIVATION_MAX_RETRIES = auto()

    INVALID_STATE = auto()

    INVOICE_NOT_FOUND = auto()

    COUPON_NOT_FOUND = auto()
    COUPON_EXPIRED = auto()
    COUPON_EXHAUSTED = auto()
    COUPON_INVALID_FOR_PLAN = auto()
    COUPON_MIN_ORDER_NOT_MET = auto()
    COUPON_ALREADY_USED = auto()

    TAX_NOT_FOUND = auto()
    TAX_INACTIVE = auto()

    EXCHANGE_RATE_NOT_FOUND = auto()
    EXCHANGE_RATE_INVALID = auto()

    REFUND_NOT_FOUND = auto()
    REFUND_INVALID_AMOUNT = auto()
    REFUND_EXCEEDS_ORDER = auto()
    REFUND_ORDER_NOT_PAID = auto()

    SETTING_NOT_FOUND = auto()
    SETTING_KEY_EXISTS = auto()
    ADMIN_CANNOT_MODIFY_SELF = auto()

    WALLET_INSUFFICIENT_AVAILABLE = auto()
    WALLET_FREEZE_NOT_FOUND = auto()
    WALLET_FREEZE_EXCEEDS_BALANCE = auto()
    WALLET_FREEZE_ALREADY_RELEASED = auto()

    REPORT_INVALID_PERIOD = auto()

    ZAINCASH_INIT_FAILED = auto()
    ZAINCASH_CALLBACK_INVALID = auto()
    ZAINCASH_TRANSACTION_NOT_FOUND = auto()
    QICARD_INIT_FAILED = auto()
    QICARD_WEBHOOK_INVALID = auto()
    QICARD_TRANSACTION_NOT_FOUND = auto()
    QICARD_VERIFICATION_FAILED = auto()
    QICARD_CANCEL_FAILED = auto()
    QICARD_REFUND_FAILED = auto()

    SMS_INIT_FAILED = auto()
    SMS_SEND_FAILED = auto()
    SMS_PROVIDER_AUTH_FAILED = auto()
    SMS_PROVIDER_BALANCE_LOW = auto()
    SMS_OTP_VERIFICATION_FAILED = auto()

    ESIM_ORDER_FAILED = auto()
    ESIM_APPLY_FAILED = auto()
    ESIM_INSTALL_FAILED = auto()
    ESIM_CATALOGUE_FAILED = auto()
    ESIM_CALLBACK_INVALID = auto()

    SUPPORT_TICKET_NOT_FOUND = auto()
    SUPPORT_TICKET_CLOSED = auto()
    SUPPORT_TICKET_ACCESS_DENIED = auto()
    SUPPORT_MESSAGE_EMPTY = auto()
    SUPPORT_CANNOT_ASSIGN_TO_SELF = auto()

    REFERRAL_CODE_NOT_FOUND = auto()
    REFERRAL_CODE_INVALID = auto()
    REFERRAL_SELF_REFERRAL = auto()
    REFERRAL_ALREADY_REFERRED = auto()
    REFERRAL_NOT_QUALIFIED = auto()
    FEATURE_DISABLED = auto()

    NOT_FOUND = auto()
    METHOD_NOT_ALLOWED = auto()


ERROR_STATUS_MAP: dict[ErrorCode, int] = {
    ErrorCode.SUCCESS: 200,
    ErrorCode.AUTH_INVALID_OTP: 401,
    ErrorCode.AUTH_EXPIRED_OTP: 401,
    ErrorCode.AUTH_MAX_ATTEMPTS: 429,
    ErrorCode.AUTH_BLOCKED: 423,
    ErrorCode.AUTH_INVALID_TOKEN: 401,
    ErrorCode.AUTH_TOKEN_EXPIRED: 401,
    ErrorCode.AUTH_TOKEN_REVOKED: 401,
    ErrorCode.AUTH_UNAUTHORIZED: 401,
    ErrorCode.AUTH_FORBIDDEN: 403,
    ErrorCode.AUTH_PHONE_EXISTS: 409,
    ErrorCode.AUTH_PHONE_NOT_FOUND: 404,
    ErrorCode.AUTH_INVALID_REFRESH: 401,
    ErrorCode.AUTH_2FA_REQUIRED: 401,
    ErrorCode.AUTH_2FA_INVALID: 401,
    ErrorCode.AUTH_DEVICE_REQUIRED: 401,
    ErrorCode.AUTH_DEVICE_SESSION_EXPIRED: 401,
    ErrorCode.VALIDATION_MISSING_FIELD: 422,
    ErrorCode.VALIDATION_INVALID_PHONE: 422,
    ErrorCode.VALIDATION_INVALID_EMAIL: 422,
    ErrorCode.VALIDATION_INVALID_AMOUNT: 422,
    ErrorCode.VALIDATION_INVALID_CURRENCY: 422,
    ErrorCode.VALIDATION_INVALID_LANGUAGE: 422,
    ErrorCode.VALIDATION_INVALID_TIMEZONE: 422,
    ErrorCode.VALIDATION_INVALID_UUID: 422,
    ErrorCode.VALIDATION_INVALID_ENUM: 422,
    ErrorCode.VALIDATION_EXCEEDS_MAX_LENGTH: 422,
    ErrorCode.VALIDATION_BELOWS_MIN_LENGTH: 422,
    ErrorCode.VALIDATION_INVALID_JSON: 400,
    ErrorCode.VALIDATION_INVALID_CONTENT_TYPE: 415,
    ErrorCode.VALIDATION_BODY_TOO_LARGE: 413,
    ErrorCode.VALIDATION_IDEMPOTENCY_REUSE: 409,
    ErrorCode.VALIDATION_INVALID_PARAMETER: 422,
    ErrorCode.ORDER_NOT_FOUND: 404,
    ErrorCode.ORDER_ALREADY_PAID: 409,
    ErrorCode.ORDER_ALREADY_PROCESSED: 409,
    ErrorCode.ORDER_EXPIRED: 410,
    ErrorCode.ORDER_CANCELLED: 410,
    ErrorCode.ORDER_INVALID_STATUS: 409,
    ErrorCode.PLAN_NOT_FOUND: 404,
    ErrorCode.PLAN_UNAVAILABLE: 410,
    ErrorCode.PLAN_INACTIVE: 410,
    ErrorCode.PLAN_COUNTRY_UNSUPPORTED: 422,
    ErrorCode.PLAN_HAS_ORDERS: 409,
    ErrorCode.WALLET_INSUFFICIENT_BALANCE: 402,
    ErrorCode.WALLET_NOT_FOUND: 404,
    ErrorCode.WALLET_TRANSACTION_FAILED: 500,
    ErrorCode.PAYMENT_FAILED: 502,
    ErrorCode.PAYMENT_TIMEOUT: 504,
    ErrorCode.PAYMENT_DECLINED: 402,
    ErrorCode.PAYMENT_CANCELLED: 410,
    ErrorCode.PAYMENT_INVALID_SIGNATURE: 401,
    ErrorCode.PAYMENT_DUPLICATE: 409,
    ErrorCode.PAYMENT_REFUND_FAILED: 502,
    ErrorCode.PAYMENT_METHOD_UNSUPPORTED: 422,
    ErrorCode.PROVIDER_UNAVAILABLE: 503,
    ErrorCode.PROVIDER_TIMEOUT: 504,
    ErrorCode.PROVIDER_INVALID_RESPONSE: 502,
    ErrorCode.PROVIDER_AUTH_FAILED: 502,
    ErrorCode.PROVIDER_RATE_LIMITED: 429,
    ErrorCode.PROVIDER_INSUFFICIENT_BALANCE: 402,
    ErrorCode.PROVIDER_BUNDLE_NOT_FOUND: 404,
    ErrorCode.RATE_LIMIT_EXCEEDED: 429,
    ErrorCode.RATE_LIMIT_AUTH_EXCEEDED: 429,
    ErrorCode.INTERNAL_ERROR: 500,
    ErrorCode.DATABASE_ERROR: 500,
    ErrorCode.DATABASE_CONNECTION_ERROR: 503,
    ErrorCode.DATABASE_INTEGRITY_ERROR: 409,
    ErrorCode.MAINTENANCE_MODE: 503,
    ErrorCode.USER_NOT_FOUND: 404,
    ErrorCode.USER_ACCOUNT_DELETED: 410,
    ErrorCode.ESIM_NOT_FOUND: 404,
    ErrorCode.ESIM_EXPIRED: 410,
    ErrorCode.ESIM_INVALID_STATUS: 409,
    ErrorCode.INVOICE_NOT_FOUND: 404,
    ErrorCode.COUPON_NOT_FOUND: 404,
    ErrorCode.COUPON_EXPIRED: 410,
    ErrorCode.COUPON_EXHAUSTED: 410,
    ErrorCode.COUPON_INVALID_FOR_PLAN: 422,
    ErrorCode.COUPON_MIN_ORDER_NOT_MET: 422,
    ErrorCode.COUPON_ALREADY_USED: 409,
    ErrorCode.TAX_NOT_FOUND: 404,
    ErrorCode.TAX_INACTIVE: 410,
    ErrorCode.EXCHANGE_RATE_NOT_FOUND: 404,
    ErrorCode.EXCHANGE_RATE_INVALID: 422,
    ErrorCode.INVALID_STATE: 409,
    ErrorCode.REFUND_NOT_FOUND: 404,
    ErrorCode.REFUND_INVALID_AMOUNT: 422,
    ErrorCode.REFUND_EXCEEDS_ORDER: 422,
    ErrorCode.REFUND_ORDER_NOT_PAID: 409,
    ErrorCode.WALLET_INSUFFICIENT_AVAILABLE: 402,
    ErrorCode.WALLET_FREEZE_NOT_FOUND: 404,
    ErrorCode.WALLET_FREEZE_EXCEEDS_BALANCE: 422,
    ErrorCode.WALLET_FREEZE_ALREADY_RELEASED: 409,
    ErrorCode.REPORT_INVALID_PERIOD: 422,
    ErrorCode.ZAINCASH_INIT_FAILED: 502,
    ErrorCode.ZAINCASH_CALLBACK_INVALID: 400,
    ErrorCode.ZAINCASH_TRANSACTION_NOT_FOUND: 404,
    ErrorCode.QICARD_INIT_FAILED: 502,
    ErrorCode.QICARD_WEBHOOK_INVALID: 400,
    ErrorCode.QICARD_TRANSACTION_NOT_FOUND: 404,
    ErrorCode.QICARD_VERIFICATION_FAILED: 502,
    ErrorCode.QICARD_CANCEL_FAILED: 502,
    ErrorCode.QICARD_REFUND_FAILED: 502,
    ErrorCode.SMS_INIT_FAILED: 502,
    ErrorCode.SMS_SEND_FAILED: 502,
    ErrorCode.SMS_PROVIDER_AUTH_FAILED: 502,
    ErrorCode.SMS_PROVIDER_BALANCE_LOW: 402,
    ErrorCode.SMS_OTP_VERIFICATION_FAILED: 400,
    ErrorCode.ESIM_ORDER_FAILED: 502,
    ErrorCode.ESIM_APPLY_FAILED: 502,
    ErrorCode.ESIM_INSTALL_FAILED: 502,
    ErrorCode.ESIM_CATALOGUE_FAILED: 502,
    ErrorCode.ESIM_CALLBACK_INVALID: 400,
    ErrorCode.SUPPORT_TICKET_NOT_FOUND: 404,
    ErrorCode.SUPPORT_TICKET_CLOSED: 409,
    ErrorCode.SUPPORT_TICKET_ACCESS_DENIED: 403,
    ErrorCode.SUPPORT_MESSAGE_EMPTY: 422,
    ErrorCode.SUPPORT_CANNOT_ASSIGN_TO_SELF: 409,
    ErrorCode.REFERRAL_CODE_NOT_FOUND: 404,
    ErrorCode.REFERRAL_CODE_INVALID: 422,
    ErrorCode.REFERRAL_SELF_REFERRAL: 409,
    ErrorCode.REFERRAL_ALREADY_REFERRED: 409,
    ErrorCode.REFERRAL_NOT_QUALIFIED: 409,
    ErrorCode.FEATURE_DISABLED: 403,
    ErrorCode.SETTING_NOT_FOUND: 404,
    ErrorCode.SETTING_KEY_EXISTS: 409,
    ErrorCode.ADMIN_CANNOT_MODIFY_SELF: 422,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.METHOD_NOT_ALLOWED: 405,
}


class AppError(Exception):
    def __init__(
        self,
        code: ErrorCode,
        data: Any = None,
        status: int | None = None,
    ) -> None:
        self.code = code
        self.data = data
        self.status = status or ERROR_STATUS_MAP.get(code, 500)
        super().__init__(self.code)
